# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Apoplexy_config = debug_x64
  raylib_config = debug_x64

else ifeq ($(config),debug_x86)
  Apoplexy_config = debug_x86
  raylib_config = debug_x86

else ifeq ($(config),debug_arm64)
  Apoplexy_config = debug_arm64
  raylib_config = debug_arm64

else ifeq ($(config),release_x64)
  Apoplexy_config = release_x64
  raylib_config = release_x64

else ifeq ($(config),release_x86)
  Apoplexy_config = release_x86
  raylib_config = release_x86

else ifeq ($(config),release_arm64)
  Apoplexy_config = release_arm64
  raylib_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Apoplexy raylib

ifeq ($(OS),Windows_NT)
  EXEEXT = .exe
  RUN_PREFIX =
else
  EXEEXT =
  RUN_PREFIX = ./
endif

ifneq (,$(findstring release,$(config)))
  APOPLEXY_BINDIR = bin/Release
else
  APOPLEXY_BINDIR = bin/Debug
endif

APOPLEXY_EXE = $(APOPLEXY_BINDIR)/apoplexy$(EXEEXT)

.PHONY: all clean help run $(PROJECTS) 

all: $(PROJECTS)
	@echo "Built $(APOPLEXY_EXE)"
	@echo "Run it with: $(RUN_PREFIX)$(APOPLEXY_EXE)"

run: all
	@$(RUN_PREFIX)$(APOPLEXY_EXE)

Apoplexy: raylib
ifneq (,$(Apoplexy_config))
	@echo "==== Building Apoplexy ($(Apoplexy_config)) ===="
	@${MAKE} --no-print-directory -C . -f Apoplexy.make config=$(Apoplexy_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C . -f raylib.make config=$(raylib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Apoplexy.make clean
	@${MAKE} --no-print-directory -C . -f raylib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   run"
	@echo "   clean"
	@echo "   Apoplexy"
	@echo "   raylib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
